#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

go build -v

install -Dm 755 punfed "$1/usr/bin/punfed"
install -Dm 755 runtime/config/config.toml "$1/etc/punfed/config.toml"

install -Dm 755 punfed.run "$1/etc/sv/punfed/run"
ln -sf /run/runit/supervise.mpd "$1/etc/sv/punfed/supervise"
